SELECT
    YEAR(CREATED_AT) AS YEAR,
    MONTH(CREATED_AT) AS MONTH,
    COUNT(CASE WHEN CATEGORY = 1 THEN 1 END) AS CANCEL_COUNT,
    SUM(CASE WHEN CATEGORY = 1 THEN ABS(AMOUNT) ELSE 0 END) AS AMOUNT
FROM
    CARD_USAGES
GROUP BY
    YEAR(CREATED_AT), MONTH(CREATED_AT)
ORDER BY
    YEAR(CREATED_AT) DESC, MONTH(CREATED_AT) DESC;
